name: Share data between jobs

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1 # or alternative dependency management
    - uses: php-actions/phpunit@v1
    

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: PHPUnit tests
      uses: php-actions/phpunit@v1
      with:
        config: phpunit/phpunit.xml
        memory: 256M
